### ISSUE TITLE
UI Crash clicking close button of validation errors banners

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#10076]
**Setup**
- Rancher UI version: master `d0f8fe31f8`

**Describe the bug**

The UI crashes if the user clicks to close the validation banners

**To Reproduce**

- Go to Cluster Management -> Create -> Harvester Cluster
- Add the cluster name and click on 'Create' button.
- It show up validation banners for machine pools missing fields
- Click on close one of the banner's close button

**Result**
The UI crashes: 

```
client.js:116 TypeError: handler.apply is not a function
    at invokeWithErrorHandling (vue.runtime.esm.js:3017:1)
    at VueComponent.invoker (vue.runtime.esm.js:1810:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:3017:1)
    at Vue.$emit (vue.runtime.esm.js:3716:1)
    at VueComponent.closeError (CruResource.vue:294:1)
    at close (CruResource.vue:52:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:3017:1)
    at Proxy.invoker (vue.runtime.esm.js:1815:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:3017:1)
    at Vue.$emit (vue.runtime.esm.js:3716:1)
_callee$ @ client.js:116

```

**Expected Result**

The banners shoul be closed without errors

**Screenshots**

![image](https://github.com/rancher/dashboard/assets/26394656/e13a2d1a-d160-409a-a573-37e21dbe8d67)

![image](https://github.com/rancher/dashboard/assets/26394656/4ae03dda-a63f-4c06-b52d-320a33596b5e)

**Additional context**

Harvester clusters creation

**Comment by a110605** [comment]
The issue can't be reproducibled on 

- Rancher v2.10.4.
https://github.com/user-attachments/assets/613df493-310e-4155-8e1a-00217c212c54


- Rancher 2.11.0

https://github.com/user-attachments/assets/19a67afb-417c-4e8a-8f5a-aed9b9ba8180
