### ISSUE TITLE
[BUG] [BACKPORT v2.8] Apps don't appear for standard user in 2.8 with certain conditions in place.

### ISSUE THREAD

**Issue by ericpromislow** [rancher/dashboard#10866]
Note that this issue doesn't happen in 2.9

**Setup**
- Rancher version: 2.8
- Rancher UI Extensions: none
- Browser type & version: Firefox 124.0.2 

**Describe the bug**
Three apps are installed by admin, and the standard user ("user01") has been given limited access.
The InstalledApps count field reports 1, 2, or 3 apps depending on which namespaces have been selected,
but no apps appear in the details table.

**To Reproduce**
Here's a repro that I've been working with. I'm running the upstream cluster on Rancher Desktop (1.12.3, k8s 1.26.14, moby, helm 2.16.8-rancher2, Rancher-Machine:
v0.15.0-rancher100) and install it like so:

First, run `ngrok` so the cluster is publicly accessible:
```

$ ngrok http --inspect=false [https://localhost:443](https://localhost/)

```

Set `NGROK1` to the domain of whatever `ngrok` reports it's forwarding to `[https://localhost:443](https://localhost/)` (without the protocol, e.g.:

```

NGROK1=123456.ngrok.app

```

). Then install rancher 2.7.5 with helm to use that domain:

```

$ helm upgrade -install cert-manager --namespace cert-manager cert-manager/cert-manager --set installCRDs=true --set "extraArgs[0]=-enable-certificate-owner-ref=true" --create-namespace --wait --timeout=10m

$ helm install rancher rancher-latest/rancher --version 2.7.5 --namespace cattle-system --set hostname="$NGROK1" --wait --timeout=10m --create-namespace

```

Once I have the upstream rancher running:

```

1. Create a downstream cluster

2. Create new standard user

Global: U&A | Create

user01: (use a strong password - this cluster is on the full internet)

3. Create a project in downstream

Click on project downstream

sidebar menu: Projects/Namespaces:

Create Project - proj01

proj01 - no members
Create ns ns01 in proj01

4. Create a cluster role

    back to main cluster view
    sidebar menu U & A
     -  submenu Roles
     - Choose "Cluster" from Global | Cluster | Project/Namespace
     - [Create Cluster Role]

Name: rt01 

Leave 
Cluster Creator Default: No (the default)
Locked: No (the default)

Verbs: Get List Watch  
Resource: apps 
API Groups: catalog.cattle.io

4.2. k edit rt01 and add:

    go to local
    start up a shell
    wait

kubectl edit RoleTemplate <the older role>

Add to template `rt01` at the same level as `resources`

```
resourceNames

    rancher-monitoring 
    ```

5. Create the project role

U&A | Role:   Project/Namespaces

[Create Project/Namespaces Role]

projRole01

Cluster Creator Default: No (the default)
Locked: No (the default)

Verbs: Get List Watch Create  Update Delete
Resource: apps 
API Groups: catalog.cattle.io

6. Installing monitoring in downstream

Go to the main cluster dashboard for downstream

[Install Monitoring] => Monitoring: [Install]
=> install version 102.3+up40.1.2
   install into Project (None) or proj01?  --- I'm choosing `proj01`

    leave other checkboxes unchecked (default)
    accept Step 2 defaults -> [Install]

7. Install app Argo in namespace ns01 (as admin)  in the downstream cluster *in
the namespace ns01*

    Click on Argo in the Apps window
    Assure that the `Namespace` dropdown is set to `ns01`
    Name: `argo-cd`

Leave the 'customize Helm options before install' checkbox blank

[Next]

Just press [Install]

8. View Installed Apps - go to All Namespaces

    just to verify

9. Create constrained rols:

9.1. Add user01 to cluster perms rt01:

    Cluster / Cluster & Project Members
    [Add]
    Select Member: user01
    Cluster Permissions: rt01
    [Create]

9.2. Add user01 to project proj01, with rt projRole01

    Click on 'Project Membership'
    proj01: [Add]
    Select Member: user01
    Project Permissions: projRole01

10. Bring up Developer Tools: Network ALL

Filter: -status-code:200 ?

11. View [cluster apps|installed app] as admin - ok

    see `argo-cd`

12. Logout, login as user01, and check cluster apps again:

Failure in Dev tools Network view

GET https://<DOMAIN>/k8s/clusters/c-m-5mkcpr6j/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts?chartName=shipa&link=icon&version=1.8.0

HTTP/2 500 

13. Trying to launch `kubectl shell`:

'Connecting...'
'Disconnected'

    can't use it

The `Installed Apps` thing is stuck at `Loading 1/15` spinner.

******************************************************************

14. BUT login as admin, and bring up the kubectl shell:

Get strings for `DOMAIN`, `CLUSTER` and `TOKEN` by looking at the network xhr calls for this URL – important: `TOKEN` is for `user01`, not `admin`

$ curl -kvL https://domain/k8s/clusters/CLUSTER/v1/catalog.cattle.io.apps -H "Cookie: R_SESS=token-TOKEN"
=>
HTTP/2 500

15. Look at the logs:

    Log in as admin
    -> Downstream cluster
    -> launch kubectl shell
    % kubectl logs pod/cattle-cluster-agent-STEM -n cattle-system --previous

...
time="2024-03-20T20:48:19Z" level=error msg="Error during subscribe websocket: close sent"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f664a1]

goroutine 57308 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*UnstructuredList).GetResourceVersion(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/apis/meta/v1/unstructured/unstructured_list.go:156
github.com/rancher/steve/pkg/stores/partition.(*ParallelPartitionLister).feeder.func2()
        /go/pkg/mod/github.com/rancher/steve@v0.0.0-20230609202141-bf2e9655f5dd/pkg/stores/partition/parallel.go:190 +0x301
```

**Result**
See above

**Expected Result**
See above

**Comment by gaktive** [comment]
Internal reference: SURE-6972
Not reproducible in 2.9-head only 2.8.x

**Comment by IsaSih** [comment]
Tests pass on v2.8-68e5d43e449fcd3ef73baf1caee98da6f0104eed-head

![Image](https://github.com/user-attachments/assets/42f676d7-1b80-420e-be90-97ffba9788dc)
