### ISSUE TITLE
Vue3: Navigating from Virtualisation to Continues Integration shows full page error (in dev?)

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11770]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- a dev full page error is shown when navigating from Virtualization Management to Continues Integration
- error not shown on refresh of Continuous Integration
- Harvester code lives in harvester-manager built-in extension

**To Reproduce**
- Select Virtualization Management (page errors, possibly related, see https://github.com/rancher/dashboard/issues/11769)
- Select Continues Integration

**Result**
Full page error

```
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading '__asyncLoader')
TypeError: Cannot read properties of undefined (reading '__asyncLoader')
    at isAsyncWrapper (https://localhost:8005/js/chunk-vendors.js:13145:40)
    at unmount (https://localhost:8005/js/chunk-vendors.js:16952:40)
    at unmountComponent (https://localhost:8005/js/chunk-vendors.js:17074:13)
    at unmount (https://localhost:8005/js/chunk-vendors.js:16959:13)
    at unmountChildren (https://localhost:8005/js/chunk-vendors.js:17103:13)
    at unmount (https://localhost:8005/js/chunk-vendors.js:16977:17)
    at unmountChildren (https://localhost:8005/js/chunk-vendors.js:17103:13)
    at unmount (https://localhost:8005/js/chunk-vendors.js:16977:17)
    at unmountComponent (https://localhost:8005/js/chunk-vendors.js:17074:13)
    at unmount (https://localhost:8005/js/chunk-vendors.js:16959:13)
ERROR
Cannot read properties of null (reading 'emitsOptions')
TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (https://localhost:8005/js/chunk-vendors.js:11963:29)
    at updateComponent (https://localhost:8005/js/chunk-vendors.js:16411:13)
    at processComponent (https://localhost:8005/js/chunk-vendors.js:16365:13)
    at patch (https://localhost:8005/js/chunk-vendors.js:15963:21)
    at patchBlockChildren (https://localhost:8005/js/chunk-vendors.js:16268:13)
    at patchElement (https://localhost:8005/js/chunk-vendors.js:16176:13)
    at processElement (https://localhost:8005/js/chunk-vendors.js:16043:13)
    at patch (https://localhost:8005/js/chunk-vendors.js:15960:21)
    at patchBlockChildren (https://localhost:8005/js/chunk-vendors.js:16268:13)
    at patchElement (https://localhost:8005/js/chunk-vendors.js:16176:13)
ERROR
Cannot read properties of null (reading 'nextSibling')
TypeError: Cannot read properties of null (reading 'nextSibling')
    at nextSibling (https://localhost:8005/js/chunk-vendors.js:20323:31)
    at getNextHostNode (https://localhost:8005/js/chunk-vendors.js:17113:16)
    at patch (https://localhost:8005/js/chunk-vendors.js:15931:22)
    at patchBlockChildren (https://localhost:8005/js/chunk-vendors.js:16268:13)
    at patchElement (https://localhost:8005/js/chunk-vendors.js:16176:13)
    at processElement (https://localhost:8005/js/chunk-vendors.js:16043:13)
    at patch (https://localhost:8005/js/chunk-vendors.js:15960:21)
    at patchBlockChildren (https://localhost:8005/js/chunk-vendors.js:16268:13)
    at patchElement (https://localhost:8005/js/chunk-vendors.js:16176:13)
    at processElement (https://localhost:8005/js/chunk-vendors.js:16043:13)
```

**Expected Result**
Fleet dashboard

**Comment by rak-phillip** [comment]
Same as #11769, I suspect that Harvester will need to migrate to Vue3 before we can make any progress on this.

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

Navigation to Virtualization Manager and then to Continuous Delivery is no longer broken and no Errors are observed in the Console.
