### ISSUE TITLE
Errors thrown in console for some components if user doesn't have permissions

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#12478]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions: N/A
- Browser type & version: N/A

**Describe the bug**

Some pages show error in the console when opened as a non-admin user

**To Reproduce**

Create a new standard user with the following custom roles
 { resource: "fleetworkspaces", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},
 { resource: "gitrepos", verbs: ["list"]},
 { resource: "bundles", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},

Go to Cluster management -> Advanced -> Pod Security Admissions
**Result**
Uncaught (in promise) Error: Unknown schema for type: storage.k8s.io.storageclass
    at getters.js:24:1
    at Object.<anonymous> (getters.js:139:1)
    at Store.findAll (actions.js:196:1)
    at Array.wrappedActionHandler (vuex.esm-bundler.js:305:1)
    at Store.dispatch (vuex.esm-bundler.js:1032:1)
    at Store.boundDispatch [as dispatch] (vuex.esm-bundler.js:914:1)
    at Proxy.fetch (management.cattle.io.podsecurityadmissionconfigurationtemplate.vue:27:1)
    at Proxy.$_fetch (fetch.client.js:73:1)
    at Proxy.$fetch (fetch.client.js:53:1)
    at Proxy.beforeMount (fetch.client.js:46:1)

Cluster management -> Drivers -> Node Drivers
**Result**
entry-helpers.js:40 TypeError: Cannot read properties of undefined (reading 'activate')
    at get _availableActions (nodedriver.js:21:1)
    at Reflect.get (<anonymous>)
    at Object.get (reactivity.esm-bundler.js:492:1)
    at get availableActions (resource-class.js:842:1)
    at Reflect.get (<anonymous>)
    at Object.get (reactivity.esm-bundler.js:492:1)
    at Proxy.bulkActionsForSelection (selection.js:73:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:1)
    at get value (reactivity.esm-bundler.js:1171:1)
    at Object.get [as bulkActionsForSelection] (

**Expected Result**

No error should be shown in the console

Continuous delivery -> Git repos -> Create a new repo -> Edit YAML this repo 
**Result**
Page fails to load with the following error in the console:
entry-helpers.js:40 TypeError: Cannot read properties of null (reading 'doneOverride')
    at Proxy.render (index.vue:420:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5720:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:1)
    at instance.update (runtime-core.esm-bundler.js:5763:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:1)
    at flushJobs (runtime-core.esm-bundler.js:406:1)

**Expected Result**
Page should load and error banner should be displayed 

**Screenshots**

**Additional context**

**Comment by izaac** [comment]
Rancher version: `v2.11-a2ff78325d1768b0a52fa65a88c00a1f3cddace5-head`
UI Version: `master 8e2d825`
Firefox version: `135.0.1`

Add a repo 

I am unable to reproduce the errors on this Rancher/UI version. The standard user can navigate existing repos, workspaces and bundles without any  issue. Additionally navigating to the described sections in this issue I don't observe any console errors. ✅
