### ISSUE TITLE
Loading page displayed when transitioning from gitrepo page to status page quickly in 2.9

### ISSUE THREAD

**Issue by mmartin24** [rancher/dashboard#12502]
**Setup**
- Rancher version: `v2.9-023781e52103c45a9bbdf3cb47d60b9336321daa-head` (it is ok in 2.8 and 2.10)
- Rancher UI Extensions:
- Browser type & version: 1.71

**Describe the bug**
This is simply to note some sluggishness on UI when transitioning from gitrepo page to status page after deploying a private Azure gitrepo via ssh. 
Although the operation is completed successfully, when done quickly by [this](https://github.com/rancher/fleet-e2e/blob/main/tests/cypress/e2e/unit_tests/p0_fleet.spec.ts#L92) test with our Cypress framework does, the test [fails](https://github.com/rancher/fleet-e2e/actions/runs/11680528664/job/32523757305#step:9:288) because a loading page interferes with next action.

![2024-11-05_17-11](https://github.com/user-attachments/assets/fd3aded9-01f6-4bec-b833-4386d0c15cc7)
Following log appears:
```
vue.min.js:11 TypeError: Cannot read properties of undefined (reading 'desiredReadyClusters')
    at a.gitRepoHasClusters (fleet.cattle.io.gitrepo.vue:43:1)
    at e.get (vue.min.js:11:28262)
    at e.evaluate (vue.min.js:11:29258)
    at a.gitRepoHasClusters (vue.min.js:11:31451)
    at a (fleet.cattle.io.gitrepo.vue:1:145)
    at e._render (vue.min.js:11:45862)
    at a.r (vue.min.js:11:79765)
    at e.get (vue.min.js:11:28262)
    at e.run (vue.min.js:11:28995)
    at un (vue.min.js:11:19867)
```

**To Reproduce**

Not reproducible manually.
Our framework reproduces by:
- Deploys private azure gitrepo (credentials via Confluence [here](https://confluence.suse.com/display/~mamartin/Fleet+QA+private+repo+tests+credentials)):
```
url: git@ssh.dev.azure.com:v3/fleetqateam/fleet-qa-examples/fleet-qa-examples
branch: main
path: nginx
```
- As soon as create button is clicked, goes to status page

**Result**
Loading page is shown

**Expected Result**
Status page should be shown.

**Screenshots**

[Screencast from 05-11-24 17:09:17.webm](https://github.com/user-attachments/assets/7d6da5eb-8055-4fd1-bd74-26936f1660de)

**Additional context**
This can be workarounded giving extra time for things to settle, but I am raising this because it is OK 2.8 and 2.10 and it was OK in 2.9 until very recently.

**Comment by wanshishi** [comment]
I have encountered the same thing. In Git Repos, when I click any item, it will just stuck in loading. It was working fine until this morning and I am on Rancher Prime 2.9.3

**Comment by nwmac** [comment]
Closing as stale - can you check is this is still an issue with the latest Rancher release and re-open if so. Thank you.
