### ISSUE TITLE
Projects/Namespaces: Unable to add project member using custom option

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12828]
**Setup**
- Rancher version: 2.11
- Rancher UI Extensions:
- Browser type & version: Chrome

**Describe the bug**
User is unable to add project member using custom option (in 2.11 only)

**To Reproduce**
1. go to local/downstream cluster
2. go to Projects/Namespaces
3. click for new/existing project click Edit Config
4. under Members tab, click `Add`
5. click `Custom` option

**Result**
User is unable to add project member using custom option.
**Expected Result**
User can add project member using custom option.

**Screenshots**

https://github.com/user-attachments/assets/fc6c2565-2a70-4b9e-80aa-b7daa9e4f98e

**Additional context**
Console Error
`ProjectMemberEditor.vue:287 TypeError: Cannot read properties of undefined (reading 'locked')
    at ProjectMemberEditor.vue:197:25
    at Proxy.reduce (<anonymous>)
    at Proxy.customPermissionsUpdate (ProjectMemberEditor.vue:194:37)
    at x.run (reactivity.esm-bundler.js:190:25)
    at get value (reactivity.esm-bundler.js:1171:39)
    at Object.get [as customPermissionsUpdate] (runtime-core.esm-bundler.js:3488:30)
    at ProjectMemberEditor.vue:297:39
    at r (runtime-core.esm-bundler.js:868:19)
    at mt (runtime-core.esm-bundler.js:3025:55)
    at Proxy.u (Card.vue:77:9)`

**Comment by yonasberhe23** [comment]
Tested in:

- Rancher v2.11-3175324fa5d50695a365b7d857a9e9cb3678053b-head
- Dashboard master `6869e55`

https://github.com/user-attachments/assets/60c5ca48-8074-47f5-bf1c-9b672b7952ff
