### ISSUE TITLE
Error when selecting routes and receivers in monitoring section

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5078]
**Setup**
- Rancher version: `2.6-head Commit ID 9aaa3a7`
- Browser type & version: Chrome 97.0.4692.99 (Official Build) (x86_64)
- RKE1 Cluster - downstream ec2

**Describe the bug**
Clicking 'Routes and Receivers' throws error in console - "Cannot read properties of undefined reading action"

**To Reproduce**
1. Install monitoring
2. Refresh page
3. Click on Monitoring > Routes and Receivers

**Result**
Console Error
`TypeError: Cannot read properties of undefined (reading 'action')
    at index.vue?0119:6:161
    at f.Se [as _l] (vue.runtime.esm.js:2630:16)
    at fn (index.vue?0119:3:1266)
    at r (vue.runtime.esm.js:2590:37)
    at f.Ee [as _t] (vue.runtime.esm.js:2686:13)
    at fn (ActionDropdown.vue?cf79:3:507)
    at r (vue.runtime.esm.js:2590:37)
    at f.Ee [as _t] (vue.runtime.esm.js:2686:13)
    at f.On (v-tooltip.esm.js:4183:22)
    at f.t._render (vue.runtime.esm.js:3548:22)`
**Expected Result**
No console error

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by ronhorton** [comment]
this is a dup of https://github.com/rancher/dashboard/issues/4993 (which is fixed) closing this as dup
