### ISSUE TITLE
Cannot deploy a Cron Job workload

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5479]
**On 2.6-head commit id: `c2d8e32`**
- Deploy a cronjob workload - cron - * * * * *
- Save changes made
- Error on UI: `Cannot read properties of undefined (reading '0')`
- Error in console

```
impl.js:182 CreateEditView mixin failed to save:  TypeError: Cannot read properties of undefined (reading '0')
    at f.saveWorkload (index.vue:581:1)
    at child-hook.js:37:34
    at d (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at Generator.O.forEach.t.<computed> [as next] (runtime.js:97:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
```

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `c2d8e32`**

I am able to deploy Cron Job type workload with no error
