### ISSUE TITLE
[project monitoring v2] create receiver in AlertmanagerConfig - no receivers shown - page blank

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5812]
**Setup**
- Rancher version: `2.6-head Commit ID eb03517`
- Browser type & version: `chrome latest`

**Describe the bug**

**To Reproduce**
1. monitoring > alerting > alertmanagerconfigs
2. create alertmanager
3. click existing alertmanagerconfig
4. click 'add reciever'

**Result**
blank page errors in console:
`TypeError: Cannot read properties of undefined (reading 'length')
    at f.r (receiverConfig.vue?bee0:4:546)
    at f.t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)
    at _n.get (vue.runtime.esm.js:4479:25)
    at new _n (vue.runtime.esm.js:4468:12)
    at t (vue.runtime.esm.js:4073:3)
    at f.$n.$mount (vue.runtime.esm.js:8415:10)
    at init (vue.runtime.esm.js:3118:13)
    at vue.runtime.esm.js:5978:9
    at v (vue.runtime.esm.js:5925:9)`

`vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'resourceFields')
    at f.data (receiverConfig.vue:126:1)
    at f.<anonymous> (vue.runtime.esm.js:1219:51)
    at vue.runtime.esm.js:4748:17
    at vue.runtime.esm.js:4705:7
    at An (vue.runtime.esm.js:4642:5)
    at f.t._init (vue.runtime.esm.js:5006:5)
    at new f (vue.runtime.esm.js:5154:12)
    at vue.runtime.esm.js:3283:10
    at init (vue.runtime.esm.js:3114:45)
    at vue.runtime.esm.js:5978:9`

**Expected Result**
when clicking existing alertmanager, expect the config for that manager to load with ability to add receivers

**Screenshots**
<img width="1599" alt="Screen Shot 2022-05-03 at 11 27 55 AM" src="https://user-images.githubusercontent.com/89212856/166484682-9e184df3-02f1-464a-8424-32803018548b.png">

**Comment by ronhorton** [comment]
after creating receiver, still not seeing receivers listed.

**Comment by gaktive** [comment]
Doesn't happen all the time. Based on discussion, a spinner should help with time to load.

**Comment by ronhorton** [comment]
different error this morning, but same effect:

`vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'spec')
    at f.namespaceMapper (helm.cattle.io.projecthelmchart.vue:49:34)
    at Array.map (<anonymous>)
    at f.namespaces (NameNsDescription.vue:198:1)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.namespaces (vue.runtime.esm.js:4836:17)
    at f.r (NameNsDescription.vue?6e74:3:820)
    at f.t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)
    at _n.get (vue.runtime.esm.js:4479:25)`

**Comment by catherineluse** [comment]
I can't reproduce this in `v2.6-head`.

@Sean-McQ I find it odd that the error is talking about a `projecthelmchart` resource, but to my knowledge there's no dependency on that resource on this page or in the AlertmanagerConfig resource model. Have you seen that error?

**Comment by Sean-McQ** [comment]
I don't think I see projectHelmChart in the error messages above but you're right, I don't think there is a dependency between them.

**Comment by ronhorton** [comment]
**Pass**
verified in `2.6-head Commit ID 132b182`
