### ISSUE TITLE
[project monitoring v2] after creating a receiver for alertmanager config, errors when trying to load alertmanager config

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5857]
**Setup**
- Rancher version: `2.6-head Commit ID 455fdf6`
- Browser type & version: `chrome latest`

**Describe the bug**
When clicking into a saved alertmanager config, receivers/routes do not load and several errors in console

**To Reproduce**
1. create alert manager config
2. click to alert manager config details
3. create receiver
4. create route from yaml
5. save
6. click AlertmanagerConfigs

**Result**
`TypeError: Cannot read properties of undefined (reading 'map')
    at f.data (index.vue:53:1)
    at f.<anonymous> (vue.runtime.esm.js:1219:51)
    at vue.runtime.esm.js:4748:17
    at vue.runtime.esm.js:4705:7
    at An (vue.runtime.esm.js:4642:5)
    at f.t._init (vue.runtime.esm.js:5006:5)
    at new f (vue.runtime.esm.js:5154:12)
    at vue.runtime.esm.js:3283:10
    at init (vue.runtime.esm.js:3114:45)
    at vue.runtime.esm.js:5978:9`

`vue.runtime.esm.js:1888 TypeError: Cannot read properties of null (reading 'concat')
    at f.optionList (vue-select.js:1:10261)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.optionList (vue.runtime.esm.js:4836:17)
    at filteredOptions (vue-select.js:1:12284)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.filteredOptions (vue.runtime.esm.js:4836:17)
    at f.<anonymous> (vue.runtime.esm.js:503:13)
    at _n.get (vue.runtime.esm.js:4479:25)`

`vue.runtime.esm.js:1888 TypeError: Invalid attempt to spread non-iterable instance
    at t.exports (vue-select.js:1:2019)
    at t.exports (vue-select.js:1:1255)
    at findOptionFromReducedValue (vue-select.js:1:15008)
    at f.setInternalValueFromOptions (vue-select.js:1:13481)
    at f.created (vue-select.js:1:13221)
    at Qt (vue.runtime.esm.js:1854:57)
    at cn (vue.runtime.esm.js:4219:7)
    at f.t._init (vue.runtime.esm.js:5008:5)
    at new f (vue.runtime.esm.js:5154:12)
    at vue.runtime.esm.js:3283:10`

`vue.runtime.esm.js:1888 TypeError: Cannot read properties of null (reading 'attributes')
    at Object.<anonymous> (type-map.js:884:33)
    at f._headers (ResourceTable.vue:163:39)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f._headers (vue.runtime.esm.js:4836:17)
    at f.r (ResourceTable.vue?6d55:1:164)
    at f.t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)
    at _n.get (vue.runtime.esm.js:4479:25)
    at new _n (vue.runtime.esm.js:4468:12)`

**Expected Result**
alertmanagerconfig detail page loads and shows receivers & routes. 

**Screenshots**
<img width="1618" alt="Screen Shot 2022-05-06 at 11 09 06 AM" src="https://user-images.githubusercontent.com/89212856/167161233-e96cc6f9-3658-42e3-8622-5674e411071a.png">

**Additional context**
I have a second alert that I setup with the same steps, and I am not having an issue with its alert manager config details page. (ie, no errors)
<img width="1619" alt="Screen Shot 2022-05-06 at 11 18 53 AM" src="https://user-images.githubusercontent.com/89212856/167162638-0187cfb9-df2d-4cc6-b733-8e60cd24c86b.png">

**Detailed Description**

**Context**

**Comment by ronhorton** [comment]
I no longer see these errors as of `2.6-head Commit ID cac23ea`

**Comment by Sean-McQ** [comment]
I don't seem to be able to reproduce. Moving to test for now.

**Comment by ronhorton** [comment]
**Pass** Verified fixed in `2.6-head Commit ID cac23ea`

No erros, load as expected
