### ISSUE TITLE
[pkg] @rancher/create-app fails to run on dev environment

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#6059]
**Setup**
- Rancher version: v2.6-head
- Browser type & version: FF 100.0.2

**Describe the bug**

When attempting to run a development environment for a newly created package, the build will fail with:

```sh
 ERROR  Error: No files matching '/home/jordon/Documents/rancher/2upstream2serious/test/shell/**/*.{ts,js,vue}' were found.
``` 

**To Reproduce**

1. Follow the steps from [here](https://github.com/rancher/dashboard/blob/master/docs/developer/PLUGINS.md#use-case-develop-a-new-ui)
2. On the `yarn dev` step nuxt will fail to load

**Result**
```sh
[jordon@endeavour test]$ yarn dev
yarn run v1.22.19
...
...
...
 ERROR  Error: No files matching '/home/jordon/Documents/rancher/2upstream2serious/test/shell/**/*.{ts,js,vue}' were found.

  at FileEnumerator.iterateFiles (node_modules/eslint/lib/cli-engine/file-enumerator.js:317:27)
  at iterateFiles.next (<anonymous>)
  at CLIEngine.executeOnFiles (node_modules/eslint/lib/cli-engine/cli-engine.js:771:48)
  at ESLint.lintFiles (node_modules/eslint/lib/eslint/eslint.js:563:23)
  at Object.<anonymous> (node_modules/@nuxt/typescript-build/node_modules/fork-ts-checker-webpack-plugin/lib/eslint-reporter/reporter/EsLintReporter.js:133:42)
  at Generator.next (<anonymous>)
  at node_modules/@nuxt/typescript-build/node_modules/fork-ts-checker-webpack-plugin/lib/eslint-reporter/reporter/EsLintReporter.js:8:71
  at new Promise (<anonymous>)
  at __awaiter (node_modules/@nuxt/typescript-build/node_modules/fork-ts-checker-webpack-plugin/lib/eslint-reporter/reporter/EsLintReporter.js:4:12)
  at Object.getIssues (node_modules/@nuxt/typescript-build/node_modules/fork-ts-checker-webpack-plugin/lib/eslint-reporter/reporter/EsLintReporter.js:120:28)
```
**Expected Result**

The dashboard should build correctly.

**Additional context**

I removed [this line](https://github.com/rancher/dashboard/blob/b099206b8f7d3da19218afe1cda5feb00810eb8e/shell/nuxt.config.js#L614) locally and that fixed the issue with eslint - however, that led to more errors which seem to be related to #5504:

```sh
 ERROR  Failed to compile with 184 errors                                                                        friendly-errors 15:38:27

These dependencies were not found:                                                                               friendly-errors 15:38:27
                                                                                                                 friendly-errors 15:38:27
* @components/BadgeState in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/RelatedResources.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/ResourceDetail/Masthead.vue?vue&type=script&lang=js& and 6 others
* @components/Banner in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/rancher-alerting-drivers.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/monitoring/prometheus/index.vue?vue&type=script&lang=js& and 41 others
* @components/Card in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/PromptChangePassword.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/dialog/AddClusterMemberDialog.vue?vue&type=script&lang=js& and 6 others
* @components/Form/Checkbox in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/rancher-alerting-drivers.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/logging/index.vue?vue&type=script&lang=js& and 33 others
* @components/Form/Checkbox/Checkbox.vue in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/edit/provisioning.cattle.io.cluster/DrainOptions.vue?vue&type=script&lang=js&
* @components/Form/LabeledInput in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/example.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/logging/index.vue?vue&type=script&lang=js& and 50 others
* @components/Form/Radio in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/monitoring/alerting/index.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/monitoring/grafana/index.vue?vue&type=script&lang=js& and 28 others
* @components/Form/Radio/RadioGroup.vue in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/PromptRestore.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/edit/provisioning.cattle.io.cluster/DrainOptions.vue?vue&type=script&lang=js&
* @components/Form/TextArea in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/form/ArrayList.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/edit/management.cattle.io.setting.vue?vue&type=script&lang=js& and 1 other
* @components/LabeledTooltip in ./node_modules/cache-loader/dist/cjs.js??ref--5-0!./node_modules/thread-loader/dist/cjs.js??ref--5-1!./node_modules/babel-loader/lib??ref--5-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/form/LabeledSelect.vue?vue&type=script&lang=js&
* pkg/rancher-components/src/components/Banner/Banner.vue in ./node_modules/babel-loader/lib??ref--15-0!./node_modules/ts-loader??ref--15-1!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/form/Footer.vue?vue&type=script&lang=ts&
                                                                                                                 friendly-errors 15:38:27
To install them, you can run: npm install --save @components/BadgeState @components/Banner @components/Card @components/Form/Checkbox @components/Form/Checkbox/Checkbox.vue @components/Form/LabeledInput @components/Form/Radio @components/Form/Radio/RadioGroup.vue @components/Form/TextArea @components/LabeledTooltip pkg/rancher-components/src/components/Banner/Banner.vue
```

**Comment by nwmac** [comment]
@jordojordo i think this is fixed now?
