### ISSUE TITLE
Fleet Bundles is not available

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6317]
**On 2.6head commit id: `c91dcaf`**

- Deploy RKE1 and RKE2 clusters
- Navigate to Continuous Delivery --> Advanced --> Bundles page.
- Nothing is loaded
- Error in console:

```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'summary')
    at fn (PlusMinus.vue:3:21)
    at r (vue.runtime.esm.js:2605:37)
    at f.Re [as _t] (vue.runtime.esm.js:2701:7)
    at fn (settings.js:3:184)
    at r (vue.runtime.esm.js:2605:37)
    at f.Re [as _t] (vue.runtime.esm.js:2701:7)
    at grouping.js:12:344
    at f.Re [as _t] (vue.runtime.esm.js:2706:47)
    at grouping.js:10:221
    at f.Ce [as _l] (vue.runtime.esm.js:2646:16)
```

**Note:**

- FLeet controller and App are in bad state. 
- Error on fleet controller: `17 mins ago	Failed to pull image "rancher/fleet:v0.3.10-rc1": rpc error: code = Unknown desc = Error response from daemon: manifest for rancher/fleet:v0.3.10-rc1 not found: manifest unknown: manifest unknown`

**Comment by sowmyav27** [comment]
**On 2.6head commit id: `2c21373`**

- Deploy RKE1 and RKE2 clusters
- Navigate to Continuous Delivery --> Advanced --> Bundles page.
- Page is loaded. No bundles displayed. No error in console.

**Comment by sowmyav27** [comment]
After an offline chat with @aalves08  Closing this issue since we aren't able to reproduce this.
