### ISSUE TITLE
`Cannot read properties of undefined (reading 'spec')` error in console after navigate to cluster from the hamberger menu

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6324]
**On 2.6head commit id: `c91dcaf`**

- Deploy rke1/rke2 clusters
- From the left hamburger menu, select a cluster and click on the cluster to navigate to "Cluster Explorer"
- Error is seen in console

```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'spec')
    at f.<anonymous> (EtcdInfoBanner.vue?897d:1:325)
    at t._render (vue.runtime.esm.js:3569:22)
    at f.r (vue.runtime.esm.js:4081:21)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.run (vue.runtime.esm.js:4570:22)
    at Sn (vue.runtime.esm.js:4326:13)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
    at ce (vue.runtime.esm.js:1915:12)
```

**Comment by richard-cox** [comment]
Think I hit this whilst doing the dynamic loading, the stack trace is misleading and the actual error is in `/shell/pages/c/_cluster/explorer/index.vue` due to `currentCluster.spec.description`. Root cause i think is the `currentCluster` disappearing during `loadCluster`... however the old content is reloaded expecting it to be there. 

There's a fix incoming, but a safe computed `currentCluster?.spec.description` would be a good stop gape
