### ISSUE TITLE
Unable to launch Rancher UI on latest 2.6head

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6558]
- Launch Rancher on latest 2.6-head 
- UI fails to load
- Error in console:

```
DOMException: Failed to construct 'Worker': Script at 'https://releases.rancher.com/dashboard/latest/785bf7a.worker.js' cannot be accessed from origin 'https://Server'.
    at new x (https://releases.rancher.com/dashboard/latest/bb3c5925f775d57b1175.js:2:1279144)
    at https://releases.rancher.com/dashboard/latest/bb3c5925f775d57b1175.js:2:1306329
    at https://releases.rancher.com/dashboard/latest/bb3c5925f775d57b1175.js:2:1306399
    at https://releases.rancher.com/dashboard/latest/bb3c5925f775d57b1175.js:2:522111
    at https://releases.rancher.com/dashboard/latest/29e85e83cb619b0db4b0.js:2:154191
    at Array.forEach (<anonymous>)
    at new m (https://releases.rancher.com/dashboard/latest/29e85e83cb619b0db4b0.js:2:154163)
    at Et (https://releases.rancher.com/dashboard/latest/bb3c5925f775d57b1175.js:2:984498)
    at https://releases.rancher.com/dashboard/latest/bb3c5925f775d57b1175.js:2:1007526
    at d (https://releases.rancher.com/dashboard/latest/29e85e83cb619b0db4b0.js:2:127983)
```

**Comment by richard-cox** [comment]
This will be resolved by https://github.com/rancher/dashboard/pull/6553, which is blocked on https://github.com/rancherlabs/eio/issues/1196. The issue only affects chrome related browsers, so firefox should work

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `20d6e22`**

The Rancher UI loads.
