### ISSUE TITLE
RKE2 Cluster Creation Screen Stuck `Loading...`

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/dashboard#6566]
**Setup**
- Rancher version: 2.6-head (93a4f30d)
- Browser type & version: Chrome, Opera, fire-fox, safari all latest versions

**Describe the bug**
When creating an RKE2 cluster on AWS, the page continuously states `Loading...` and never completes preventing the creation of a cluster. The chrome console logs the following message

```
TypeError: Cannot read properties of undefined (reading 'find')
    at f.networkOptions (GlobalRoleBindings.vue:215:1)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.networkOptions (vue.runtime.esm.js:4851:17)
    at f.<anonymous> (GlobalRoleBindings.vue?146a:1:2434)
    at t._render (vue.runtime.esm.js:3569:22)
    at f.r (vue.runtime.esm.js:4081:21)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.run (vue.runtime.esm.js:4570:22)
    at Sn (vue.runtime.esm.js:4326:13)
```
There are also some logs regarding a `400` status from the API, however I also see those on 2.6.6 where the issue does _not_ reproduce. 

**To Reproduce**
Launch rancher on 2.6-head. 
Go to `Cluster Management`, and click `Create`
Enable `RKE2/K3s`
Select `Amazon EC2`
If you don't have one already, setup a cloud-credential and continue

**Result**
The page stays `Loading...` forever 

**Expected Result**
The AWS information is retrieved and the page only loads for a small amount of time

**Additional context**
It doesn't appear to be an AWS policy issue. **I am running Rancher from a local Goland IDE**

**Comment by HarrisonWAffel** [comment]
I can confirm that the merged PR has resolved the issue I encountered, I am now able to view the RKE2 cluster creation screen and am not blocked by a `Loading...` message.
