### ISSUE TITLE
Unable to access accounts and API keys as a standard user 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6639]
Setup

Rancher version: 2.6-head 76d89bd
Browser type & version: Chrome

**Describe the bug**
Once we log into rancher server, if we try to access cluster management page or Account the page is stuck in loading and never loads.

**To Reproduce**

1. Create a rancher server on v2.6-head
2. Create a standard user as an admin from Users and auth >> users with standard user permissions
3. logout as admin and log in as the standard user.
4. From user profile >> Accounts & Api keys

**Result**
Page is stuck in loading and  never loads. following console logs are seen:

```
tls.vue?230f:26 TypeError: Cannot read properties of null (reading 'indexOf')
    at f.apiUrlBase (66a1009873864594806e.js:1:39360)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.apiUrlBase (vue.runtime.esm.js:4851:17)
    at f.apiUrl (66a1009873864594806e.js:1:39519)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.apiUrl (vue.runtime.esm.js:4851:17)
    at f.<anonymous> (PromptChangePassword.vue:1:1367)
    at t._render (vue.runtime.esm.js:3569:22)

```

**Expected Result**
Expected the page to be accessible as a standard user

**Screenshots**
<img width="300" alt="acciunts" src="https://user-images.githubusercontent.com/38144301/184093694-4835e019-fb68-41ad-b673-e49ba0fb1e56.png">

**Additional context**
Works fine for admin users.

**Comment by richard-cox** [comment]
`/shell/pages/account/index.vue` `apiUrlBase` needs to ensure the two settings it uses are available to standard users and if not, we fall back correctly on  window.location.origin

**Comment by aalves08** [comment]
@anupama2501 

I've provisioned the version `2.6-head 76d89bd`, created a standard user, used the UI provided by the droplet (to eliminate potencial dev/prod build problems/discrepancies) and could access `Accounts & Api keys` fine and log out from any screen without any issue, even from a CruResource component such as RKE2 cluster creation (which could be linked to #6640 ).

<img width="776" alt="Screenshot 2022-08-11 at 11 42 00" src="https://user-images.githubusercontent.com/97888974/184116705-1f7ba78c-e7b7-413b-bf60-76c12168b0f2.png">
<img width="776" alt="Screenshot 2022-08-11 at 11 37 11" src="https://user-images.githubusercontent.com/97888974/184116715-ff1ae73b-24fa-4e4a-bc81-c08ee5f45ef1.png">
<img width="776" alt="Screenshot 2022-08-11 at 11 32 42" src="https://user-images.githubusercontent.com/97888974/184116724-a114e9e1-2b70-437c-b18c-221280515ca4.png">
<img width="776" alt="Screenshot 2022-08-11 at 11 22 48" src="https://user-images.githubusercontent.com/97888974/184116845-977252c9-9540-46ca-bede-c87c87779b89.png">
 
 Is there any way that we can have access to your system in order to do some further testing? 🙏 . Thanks
 
FYI @gaktive @richard-cox @kwwii

**Comment by anupama2501** [comment]
User was created without any global permissions assigned, therefore seeing weird behavior in the rancher server.

**Comment by anupama2501** [comment]
This seems to be the case because the user has not global role binding created:

<img width="300" alt="grbs" src="https://user-images.githubusercontent.com/38144301/184176493-2e6d0479-5296-4f37-bf63-8dacee932592.png">

Moving this to backend.
