### ISSUE TITLE
Error: Redirected when going from "/auth/verify?code=" is seen while logging in with Azure AD auth provider

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6859]
**Setup**
- Rancher version: v2.6-head 79a5328
- Browser type & version: Chrome

**Describe the bug**
While logging as an azure AD auth provider user, errors are seen in the console logs 

**To Reproduce**
1. Install rancher server on v2.6-head
2. Enable Azure AD auth provider
3. Log out from the rancher server 
4. Open network tab and console logs
5. Login as either the admin user with which azure AD was enabled or a standard user
6. Observe the console logs while logging in

**Result**
Error seen in the console logs:

```
client.js:637 Error: Redirected when going from "/auth/verify?code=0.ARcAU29LVvTrw0OAd0TFakSZClajzBgOF9lLpKQuNJhV-WsXAF0.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P-7Bu2gX9XU2ANlkPtnSIGjga_VE2WCATcLwjcAZScFbGPluRtGRJZ-FvouOACcj6tQOvo0SUBSLHFJh_pnSS9OsAQfq268GWHxGXGv88DfEDMYfpQd1CZvqxohZLqT3JIRJbyNOavVvQKAimHIPqmR4UZaUo3NalaB401AoVRokIk-sAWPLZlx7hWSO1fKgSQi0a662iSbW3P11TL-ckfsB0dzmBM6GAffcXV-ltjQOWnu9N3CnfTKq3cxIX1AXGzohNYgC240bybhJMkxPF6RuhhLDxL4agMFUBOiKxh_uRNlPoA2yyXiG9v0hK6FxoFchHplxZFlJh-Fy2DZFGRCybQZ-MwbOOHD88I99rJo72lTvlvKSKKfCdsYqIRe-_Zfdg3EJAxtVBsB4LUSgvSxQFsV1KMibheFw55KNqF2rgiWcK_MQvIQ00BZD3cUamtvSBB4FSnGpuat6LeV3P6bPo9U3-xfuBuO_YtQC47xt9iR7JtJBYwUCEKukv578Qsr5mrKQ38cHOYm3lbSN6ltmB468IVXMHzIwUjESkGvQz3YcvMvhjqhmh5bg6TTeD_lniR9qJ8h4FyjNDGuZ4YTqSdunyIwTJ9cX-5xPbPX9dvmpMn9ZWvJrto80_w&state=eyJub25jZSI6IkV3bU4ya013RHRYV1RVMm4iLCJ0byI6InZ1ZSIsInByb3ZpZGVyIjoiYXp1cmVhZCJ9&session_state=f63afaa5-b21d-4d32-a7af-60046eb67eec" to "/" via a navigation guard.
    at Pt (vue-router.esm.js:2065:15)
    at Rt (vue-router.esm.js:2024:10)
    at vue-router.esm.js:2376:17
    at Fn.f (client.js:240:5)
    at T.regeneratorRuntime.mark.regeneratorRuntime.wrap.e.context.e.context.redirect (utils.js:235:21)
    at middleware (index.vue:26:14)
    at N (utils.js:311:15)
    at j (utils.js:291:10)
    at utils.js:293:14
```

**Expected Result**
Expected no errors in the console logs

**Additional context**
- tried this with openldap auth providers and not seeing the issue
- Seeing the error on v2.6.8 rancher server as well.

**Comment by nwmac** [comment]
@anupama2501 Other than the console error, is anything broken in the UI? or is the request here purely to remove the console message?

**Comment by anupama2501** [comment]
this is purely to remove the console message @nwmac
