### ISSUE TITLE
Blank page is shown when navigating from Cluster's Project/Namespace page to Cluster Management

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7801]
**Setup**
- Rancher version: 2.7-head
- Browser type & version:

**Describe the bug**
Navigating from Cluster's Project/Namespace page to Cluster Management results in a blank page (see screenshot)

**To Reproduce**
- burger menu --> click on a cluster --> click on side nav `Cluster` /  `Projects/Namespaces` page
- Refresh
- ~nurger menu~ burger menu --> click on `Cluster Managment`

**Result**
![image](https://user-images.githubusercontent.com/18697775/209190969-359d8f58-cdfa-42c9-be60-fdb8ed2e6aab.png)

**Expected Result**
![image](https://user-images.githubusercontent.com/18697775/209191052-a74a1849-5fe3-4877-ab2c-a5d4b1ed5a46.png)

**Additional context**
Error in console (nothing in our stack)
```
console.js:31 TypeError: Cannot read properties of undefined (reading 'props')
    at vue.runtime.esm.js:1419:23
    at Wt (vue.runtime.esm.js:1521:3)
    at Wt (vue.runtime.esm.js:1535:18)
    at Fn.t.extend (vue.runtime.esm.js:5173:19)
    at Je (vue.runtime.esm.js:3203:21)
    at vue.runtime.esm.js:3443:15
    at Ze (vue.runtime.esm.js:3374:10)
    at t._c (vue.runtime.esm.js:3512:42)
    at f.<anonymous> (index.vue?aca3:1:87)
    at t._render (vue.runtime.esm.js:3569:22)
```

```
/**
 * Ensure all props option syntax are normalized into the
 * Object-based format.
 */
function normalizeProps (options, vm) {
  var props = options.props;
```

**Comment by richard-cox** [comment]
Same outcome as https://github.com/rancher/rancher/issues/39946, possibly related (though that refers to shipped code)

**Comment by mantis-toboggan-md** [comment]
That's such an interesting error message that I couldn't resist investigating:
I see a different error running the dash locally but I assume it's the same underlying problem: `TypeError: Cannot read properties of undefined (reading 'components')`. I can repro this navigating to pages other than cluster management (harvester, explorer workloads, global settings, probably more). The dash works as of [this commit](https://github.com/rancher/dashboard/commit/668ef1528734846b94373ac43fcb4e688e35dc62) and breaks with [this commit](https://github.com/rancher/dashboard/commit/c78a5c451d0a9a718cf8636bc9d01e9cdae509f5)

Consequently @richard-cox I think this bug was likely introduced by this pr: https://github.com/rancher/dashboard/pull/7329 ...unfortunately, this is a fairly substantial PR and I don't think I have time to dig further before skedaddling for the holidays.

**Comment by richard-cox** [comment]
Interesting, that's one of mine (brought in for 2.7.2). I cleaned up a lot of how the list resources are fetched in that PR. Maybe it only happens when navigating to/from certain list.

**Comment by Josh-Diamond** [comment]
Ticket #7801 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream cluster - [ I used RKE2 AWS Node driver w/ k8s `v1.24.8+rke2r1` ]
3. From hamburger menu, select cluster once its `active`
4. Navigate to `Projects/Namespaces`
5. Refresh
6. Navigate to `hamburger menu > Cluster Management`
7. Verified - All clusters accurately shown; page no longer blank; no errors seen in console

Screenshot:

`Step 7`
<img width="1593" alt="Screenshot 2023-01-06 at 12 20 36 PM" src="https://user-images.githubusercontent.com/46494969/211084194-b19060a9-d135-4b86-82fb-65a4e2269744.png">
