### ISSUE TITLE
Unable to log in on Rancher Web UI

### ISSUE THREAD

**Issue by rldourado** [rancher/dashboard#7835]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

When I try to log in Rancher Web UI, it stucks with "Loggin in..." and a spinner on the "Log in with Local User" button was.

![image](https://user-images.githubusercontent.com/2440820/173407794-0649ae23-6979-4c22-8335-495ec15e4458.png)

If I open a new browser tab and try to access rancher, a blue spinner appears and nothing more happens. In the meantime, a error message ```NavigationDuplicated: Avoided redundant navigation to current location: "/".``` shows on browser console.

![image](https://user-images.githubusercontent.com/2440820/173408062-e1ed7f0a-4783-48a8-98fc-7a4e4c5e5794.png)

**To Reproduce**
Try to log in Rancher Web UI

**Result**

**Expected Result**
I expected to access Rancher Web UI Dashboard

**Screenshots**
See above

**Additional context**
Recently I upgraded Rancher from 2.5.9 to 2.6.5. Then, I was able to log in Rancher Web UI for a few days. Now, out of the blue, it doesn't work anymore.

Error:

```NavigationDuplicated: Avoided redundant navigation to current location: "/".
    at $t (https://k8s.mppe.mp.br/dashboard/_nuxt/commons/app.33ef1205fb1fcfd94671.js:2:76164)
    at Ut.confirmTransition (https://k8s.mppe.mp.br/dashboard/_nuxt/commons/app.33ef1205fb1fcfd94671.js:2:79130)
    at Ut.transitionTo (https://k8s.mppe.mp.br/dashboard/_nuxt/commons/app.33ef1205fb1fcfd94671.js:2:78459)
    at e.push (https://k8s.mppe.mp.br/dashboard/_nuxt/commons/app.33ef1205fb1fcfd94671.js:2:81669)
    at Qt.push (https://k8s.mppe.mp.br/dashboard/_nuxt/commons/app.33ef1205fb1fcfd94671.js:2:86651)
    at l.default.push (https://k8s.mppe.mp.br/dashboard/_nuxt/app.19d73dab09087954b96b.js:2:6198908)
    at o.default.push (https://k8s.mppe.mp.br/dashboard/_nuxt/app.19d73dab09087954b96b.js:2:7011945)
    at https://k8s.mppe.mp.br/dashboard/_nuxt/app.19d73dab09087954b96b.js:2:3503323
    at $n.d (https://k8s.mppe.mp.br/dashboard/_nuxt/app.19d73dab09087954b96b.js:2:3496808)
    at E.regeneratorRuntime.mark.regeneratorRuntime.wrap.n.context.n.context.redirect (https://k8s.mppe.mp.br/dashboard/_nuxt/app.19d73dab09087954b96b.js:2:294973)
(anônimo) @ opsgenie.vue?f594:626
```

**Comment by oschrenk** [comment]
Same issue on v2.6.8

**Comment by gentoorax** [comment]
I'm getting this on current stable 2.7.1. With a fresh helm install to the point I can't actually go through the setup.

**Comment by gentoorax** [comment]
Excellent, a fix. What's the best way to get this fix into my cluster today? Or do I need to wait for it to filter down into a rancher release?

**Comment by gentoorax** [comment]
> > Excellent, a fix. What's the best way to get this fix into my cluster today? Or do I need to wait for it to filter down into a rancher release?
> 
> There's a few workarounds listed above, some can be automated. The fix though is currently targeted for v2.7.2.

Thanks for the reply, much appreciated. Unfortunately, none of the above workarounds were suitable in my situation. I was hitting this after a fresh installation of 2.7.1 on first login. So my account had never logged in before and I wasn't able to navigate to dashboard/home after trying the login either.

I will look to run rancher under docker for the time being, then re-try this when 2.7.2 is available.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head d559c2f
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 110

----------

### Testing: ###
Tested this issue with the following steps:
1. admin user (or other user) login, set `Preferences` - `Login Landing Page` - `Take me to the area I last visited`
2. Sequentially click menus in the UI: `EXPLORE CLUSTER - local`, `GLOBAL APPS - Cluster Management`
3. View API `/v1/userpreferences`，you can see `last-visited` attribute value is `{"name":"c-cluster-explorer","params":{}}`
4. Re-login user

**Result**
User is able to log in and I am not seeing the error in the console anymore
