### ISSUE TITLE
Routing in plugins (Harvester) broken on browser refresh or initial load

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#8435]
**Setup**
- Rancher version: 2.7.1
- Browser type & version: Chrome

**Describe the bug**
The routing in plugins (tested with the bundled harvester plugin) is a bit broken. The navigation from page to page works correctly. But if you are on a harvester plugin page, or if you directly enter a link to one, the correct page is not loaded and you get a blank page.

**To Reproduce**
* Go to a harvester page, like the list of VMs.
* Refresh the page in the browser

**Result**
The page is blank.

The browser dev tools shows a JS error:

```
TypeError: Cannot read properties of undefined (reading 'inStore')
    at Object.<anonymous> (type-map.js:812:53)
    at f.getGroups (default.vue:402:1)
    at default.vue:302:1
    at v (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
```

**Expected Result**
The page is correctly rendered

**Screenshots**
Im created a video to show the behaviour: 

https://user-images.githubusercontent.com/243056/225097281-1bca1cf1-6b43-42b5-8a69-4ca25f2918eb.mov

**Additional context**
This also breaks the Harvester serial and webvnc console features, because they are opened in a browser popup.

If you need access to an environment with Harvester to test, please ping me.

**Comment by bashofmann** [comment]
Harvester version is 1.1.1.

I also tested this with `release-2.7.2` and `master`. There it's also broken, but the JS error is slightly different:

```
console.js:31 TypeError: rootGetters["".concat(...)] is not a function
    at Object.<anonymous> (type-map.js:848:1)
    at VueComponent.getProductsGroups (default.vue:390:1)
    at VueComponent.getGroups (default.vue:526:1)
    at _callee2$ (default.vue:313:1)
    at tryCatch (runtime.js:63:1)
    at Generator.invoke [as _invoke] (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
```

**Comment by richard-cox** [comment]
@nwmac @aalves08 this is down as `QA/None`, given the testing in the PR are we good to close?

**Comment by nwmac** [comment]
@richard-cox Yes
