### ISSUE TITLE
Pods can not be cloned via UI since upgrade to Rancher 2.7.1

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8681]
Internal reference: SURE-6167
Reported in 2.7.1 &  2.7.2

User reports that since upgrading Rancher to version 2.7.1 they are not able to clone pods from UI : Downstream Cluster --> Workload --> Choose a pod and use the clone option, the website will stay in status "loading".  

![pod-cloning-attempt.png](https://zube.io/files/rancher/28217580f3a462d3606c12119f2955dd-pod-cloning-attempt.png)

Expected behavior:
New website with a mask should be loaded

Developer console reports : 

```
Find: [cluster] pod default/my-release-wordpress-f65d57d59-5c8lg          console.js:31 

TypeError: Cannot read properties of undefined (reading 'containers')
    at f.data (workload.js:166:38)
    at f.<anonymous> (vue.runtime.esm.js:1219:51)
    at vue.runtime.esm.js:4761:17
    at vue.runtime.esm.js:4718:7
    at In (vue.runtime.esm.js:4655:5)
    at t._init (vue.runtime.esm.js:5020:5)
    at new f (vue.runtime.esm.js:5168:12)
    at vue.runtime.esm.js:3304:10
    at init (vue.runtime.esm.js:3133:45)
    at vue.runtime.esm.js:6022:9

TypeError: Cannot read properties of undefined (reading 'containers')
    at f.data (workload.js:166:38)
    at f.<anonymous> (vue.runtime.esm.js:1219:51)
    at f.<anonymous> (vue.runtime.esm.js:1220:53)
    at vue.runtime.esm.js:4761:17
    at vue.runtime.esm.js:4718:7
    at In (vue.runtime.esm.js:4655:5)
    at t._init (vue.runtime.esm.js:5020:5)
    at new f (vue.runtime.esm.js:5168:12)
    at vue.runtime.esm.js:3304:10
    at init (vue.runtime.esm.js:3133:45)

resource-manager.js:28 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'namespace')
    at resource-manager.js:28:38
    at v (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at f.resourceManagerFetchSecondaryResources (resource-manager.js:26:88)

resource-manager.js:28  Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'namespace')
    at resource-manager.js:28:38
    at v (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at f.resourceManagerFetchSecondaryResources (resource-manager.js:26:88)
```

**Comment by nwmac** [comment]
Note: We should add test automation to prevent regression

**Comment by cnotv** [comment]
```
source-manager.js:28 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'namespace')
    at resource-manager.js:28:38
 ```

**Comment by nwmac** [comment]
@Shavindra This needs an automated test

**Comment by nwmac** [comment]
@Shavindra so this is not a generic one issue with pods? You can’t reproduce this on the local cluster?

**Comment by nwmac** [comment]
@Shavindra This is a generic issue - downstream cluster not needed - so we can create an automated test.

It may well be possible to cover this with a unit test rather than an e2e test.
