### ISSUE TITLE
When not using Weave, defining a Weave password in cluster or template manifest should error out

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8870]
Internal reference: SURE-6179
Reported in 2.6.10

Issue description:

When applying a cluster template containing a weave parameter (password in this case) and using the Canal CNI, the UI just halts with no information.  When we look at dev tools we see the following error:

```
caught Error: Property set failed: object in path "primaryResource.rancherKubernetesEngineConfig.network.weaveNetworkProvider" could not be found.
    at ke (index.js:1579:1)
    at Ce (index.js:1529:1)
    at De.set (index.js:2432:1)
    at e.n [as default] (index.js:1021:1)
    at Ce (index.js:1535:1)
    at index.js:2876:1
    at z (index.js:647:1)
    at e.setProperties (index.js:2870:1)
    at e.willSave (component.js:116:1)
    at e.n [as willSave] (index.js:442:1)
```

Business impact:
Users were left confused and dissatisfied going down a rabbit hole of more and more modifications and problematic alternatives trying to work around the issue without realizing there was a bad parameter in the template

Troubleshooting steps:
We saw the error mentioned weave and reviewed the template.  When we saw a weave parameter we removed it and were able to save the template

Repro steps:

save a template with weave password configured but Canal set as CNI

Actual behavior:
Nothing happens

Expected behavior:
UI should show a failure and meaningful error

**Comment by gaktive** [comment]
CNI plugin will be deprecated as part of Kubernetes 1.27 so we won't do this. Another ticket filed to put a warning in place to indicate that this will go away.

**Comment by gaktive** [comment]
#9556 will address the deprecation.
