### ISSUE TITLE
Loading of charts page sometimes broken

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#9205]
**Setup**
- Rancher version: 2.7.4
- Rancher UI Extensions: Elemental, Kubewarden
- Browser type & version: Chrome

**Describe the bug**
The loading of the Apps -> Charts page is sometimes broken and creates the error `Type charts not found, unable to display list`.
The only way to fix it is to log out, refresh the page and log in again. Then loading of Apps -> Charts works again

**To Reproduce**
There is no clear reproduction process. It randomly starts to break at some point.

**Result**
The charts page is broken.

**Expected Result**
The charts page should work.

**Screenshots**
<img width="996" alt="Bildschirmfoto 2023-06-24 um 11 12 24" src="https://github.com/rancher/dashboard/assets/243056/932b3951-602f-4709-a5f7-95c2c887fd26">

**Additional context**
JS errors in the console
```
Loading error Error: Type charts not found, unable to display list
    at m.setError (index.js:586:17)
    at vuex.esm.js:844:13
    at vuex.esm.js:466:7
    at Array.forEach (<anonymous>)
    at vuex.esm.js:465:11
    at m._withCommit (vuex.esm.js:624:3)
    at m.commit (vuex.esm.js:464:8)
    at commit (vuex.esm.js:409:19)
    at m.loadingError (index.js:1010:5)
    at Array.<anonymous> (vuex.esm.js:851:23)
console.js:31 (actual error) Error: Type charts not found, unable to display list
    at f.fetch (index.vue:72:1)
    at f.<anonymous> (fetch.client.js:72:31)
    at v (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at f.<anonymous> (asyncToGenerator.js:21:12)
console.js:31 Loading error location Error: loadingError
    at m.loadingError (index.js:1010:53)
    at Array.<anonymous> (vuex.esm.js:851:23)
    at m.dispatch (vuex.esm.js:516:13)
    at m.dispatch (vuex.esm.js:406:21)
    at f.fetch (index.vue:72:1)
    at f.<anonymous> (fetch.client.js:72:31)
    at v (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
console.js:31 Loading original error Error: Type charts not found, unable to display list
    at f.fetch (index.vue:72:1)
    at f.<anonymous> (fetch.client.js:72:31)
    at v (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at f.<anonymous> (asyncToGenerator.js:21:12)
console.js:31 TypeError: Cannot read properties of undefined (reading 'id')
    at Object.<anonymous> (type-map.js:974:35)
    at f.groupBy (index.vue:130:1)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.groupBy (vue.runtime.esm.js:4851:17)
    at f.Ne (index.vue:1:1336)
    at t._render (vue.runtime.esm.js:3569:22)
    at f.r (vue.runtime.esm.js:4081:21)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at new Tn (vue.runtime.esm.js:4484:12)
Xr.n.forEach.console.<computed> @ console.js:31
re @ vue.runtime.esm.js:1897
ne @ vue.runtime.esm.js:1888
te @ vue.runtime.esm.js:1848
t._render @ vue.runtime.esm.js:3571
r @ vue.runtime.esm.js:4081
Tn.get @ vue.runtime.esm.js:4495
Tn @ vue.runtime.esm.js:4484
t @ vue.runtime.esm.js:4088
Dn.$mount @ vue.runtime.esm.js:8459
init @ vue.runtime.esm.js:3137
(anonymous) @ vue.runtime.esm.js:6022
v @ vue.runtime.esm.js:5969
(anonymous) @ vue.runtime.esm.js:6521
t._update @ vue.runtime.esm.js:3960
r @ vue.runtime.esm.js:4081
Tn.get @ vue.runtime.esm.js:4495
Tn @ vue.runtime.esm.js:4484
t @ vue.runtime.esm.js:4088
Dn.$mount @ vue.runtime.esm.js:8459
init @ vue.runtime.esm.js:3137
n @ vue.runtime.esm.js:3322
(anonymous) @ vue.runtime.esm.js:6022
v @ vue.runtime.esm.js:5969
(anonymous) @ vue.runtime.esm.js:6560
t._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
Tn.get @ vue.runtime.esm.js:4495
Tn.run @ vue.runtime.esm.js:4570
Sn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
ce @ vue.runtime.esm.js:1915
Promise.then (async)
oe @ vue.runtime.esm.js:1942
pe @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Tn.update @ vue.runtime.esm.js:4560
t.$forceUpdate @ vue.runtime.esm.js:3984
(anonymous) @ vue.runtime.esm.js:8244
h @ vue.runtime.esm.js:2244
ee @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2184
(anonymous) @ vue.runtime.esm.js:7740
(anonymous) @ vue.runtime.esm.js:336
bo @ vue.runtime.esm.js:7435
(anonymous) @ vue.runtime.esm.js:7772
requestAnimationFrame (async)
(anonymous) @ vue.runtime.esm.js:7407
requestAnimationFrame (async)
yo @ vue.runtime.esm.js:7406
k @ vue.runtime.esm.js:7764
So @ vue.runtime.esm.js:7748
remove @ vue.runtime.esm.js:7841
j @ vue.runtime.esm.js:6199
T @ vue.runtime.esm.js:6173
(anonymous) @ vue.runtime.esm.js:6602
t._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
Tn.get @ vue.runtime.esm.js:4495
Tn.run @ vue.runtime.esm.js:4570
Sn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
ce @ vue.runtime.esm.js:1915
Promise.then (async)
oe @ vue.runtime.esm.js:1942
pe @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Tn.update @ vue.runtime.esm.js:4560
_t.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
jn.set @ vue.runtime.esm.js:4644
finish @ GlobalLoading.vue:14
(anonymous) @ client.js:429
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
j @ b36c37339b5bc9dfd064.js:2
_ @ vue-router.esm.js:2362
r @ vue-router.esm.js:2087
(anonymous) @ vue-router.esm.js:2088
(anonymous) @ vue-router.esm.js:2384
(anonymous) @ client.js:131
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_ @ b36c37339b5bc9dfd064.js:2
_ @ vue-router.esm.js:2362
r @ vue-router.esm.js:2087
r @ vue-router.esm.js:2091
Lt @ vue-router.esm.js:2095
zt.confirmTransition @ vue-router.esm.js:2392
zt.transitionTo @ vue-router.esm.js:2260
e.replace @ vue-router.esm.js:2618
(anonymous) @ vue-router.esm.js:3049
ee.replace @ vue-router.esm.js:3048
A.a.replace @ extend-router.js:33
A.a.applyQuery @ extend-router.js:52
category @ index.vue:230
ee @ vue.runtime.esm.js:1863
Tn.run @ vue.runtime.esm.js:4584
Sn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
ce @ vue.runtime.esm.js:1915
Promise.then (async)
oe @ vue.runtime.esm.js:1942
pe @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Tn.update @ vue.runtime.esm.js:4560
_t.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
jn.set @ vue.runtime.esm.js:4644
(anonymous) @ index.vue:42
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetch @ index.vue:37
(anonymous) @ fetch.client.js:72
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
h @ b36c37339b5bc9dfd064.js:2
f @ fetch.client.js:57
d @ fetch.client.js:29
ee @ vue.runtime.esm.js:1863
vn @ vue.runtime.esm.js:4235
t @ vue.runtime.esm.js:4058
Dn.$mount @ vue.runtime.esm.js:8459
init @ vue.runtime.esm.js:3137
n @ vue.runtime.esm.js:3322
(anonymous) @ vue.runtime.esm.js:6022
v @ vue.runtime.esm.js:5969
(anonymous) @ vue.runtime.esm.js:6560
t._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
Tn.get @ vue.runtime.esm.js:4495
Tn.run @ vue.runtime.esm.js:4570
Sn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
ce @ vue.runtime.esm.js:1915
Promise.then (async)
oe @ vue.runtime.esm.js:1942
pe @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Tn.update @ vue.runtime.esm.js:4560
t.$forceUpdate @ vue.runtime.esm.js:3984
(anonymous) @ vue.runtime.esm.js:8244
h @ vue.runtime.esm.js:2244
ee @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2184
(anonymous) @ vue.runtime.esm.js:7740
(anonymous) @ vue.runtime.esm.js:336
bo @ vue.runtime.esm.js:7435
(anonymous) @ vue.runtime.esm.js:7772
requestAnimationFrame (async)
(anonymous) @ vue.runtime.esm.js:7407
requestAnimationFrame (async)
yo @ vue.runtime.esm.js:7406
k @ vue.runtime.esm.js:7764
So @ vue.runtime.esm.js:7748
remove @ vue.runtime.esm.js:7841
j @ vue.runtime.esm.js:6199
T @ vue.runtime.esm.js:6173
(anonymous) @ vue.runtime.esm.js:6602
t._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
Tn.get @ vue.runtime.esm.js:4495
Tn.run @ vue.runtime.esm.js:4570
Sn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
ce @ vue.runtime.esm.js:1915
Promise.then (async)
oe @ vue.runtime.esm.js:1942
pe @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Tn.update @ vue.runtime.esm.js:4560
_t.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
jn.set @ vue.runtime.esm.js:4644
finish @ GlobalLoading.vue:14
(anonymous) @ client.js:429
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
j @ b36c37339b5bc9dfd064.js:2
_ @ vue-router.esm.js:2362
r @ vue-router.esm.js:2087
(anonymous) @ vue-router.esm.js:2088
(anonymous) @ vue-router.esm.js:2384
(anonymous) @ client.js:131
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_ @ b36c37339b5bc9dfd064.js:2
_ @ vue-router.esm.js:2362
r @ vue-router.esm.js:2087
r @ vue-router.esm.js:2091
Lt @ vue-router.esm.js:2095
zt.confirmTransition @ vue-router.esm.js:2392
zt.transitionTo @ vue-router.esm.js:2260
e.replace @ vue-router.esm.js:2618
(anonymous) @ vue-router.esm.js:3049
ee.replace @ vue-router.esm.js:3048
A.a.replace @ extend-router.js:33
groupSelected @ Group.vue:119
click @ Group.vue:3
ee @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
Dr.c._wrapper @ vue.runtime.esm.js:6961
console.js:31 TypeError: Cannot read properties of undefined (reading 'id')
    at Object.<anonymous> (type-map.js:974:35)
    at f.groupBy (index.vue:130:1)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.groupBy (vue.runtime.esm.js:4851:17)
    at f.Ne (index.vue:1:1336)
    at t._render (vue.runtime.esm.js:3569:22)
    at f.r (vue.runtime.esm.js:4081:21)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.run (vue.runtime.esm.js:4570:22)
```

**Comment by richard-cox** [comment]
Thanks.

We think https://github.com/rancher/dashboard/issues/9196 and https://github.com/rancher/dashboard/issues/9205 are both related to the same bug. The Kube Warden extension is missing a fix that stops extensions from grabbing generic routes (which makes the UI think it's navigating through a different extension product). Good news, this should just mean we fix and release a new kube warden, rather than having to wait for a Rancher release.

**Comment by jordojordo** [comment]
This has been fixed with the release of [Kubewarden 1.0.6](https://github.com/kubewarden/ui/releases/tag/kubewarden-1.0.6) and the update can also be found within the [ui-plugin-charts](https://github.com/rancher/ui-plugin-charts) repository. Kubewarden will need to be updated to resolve this issue.

**Comment by kravciak** [comment]
I was able to reproduce with kubewarden-ui 1.0.5, issue disappeared when I updated to kubewarden-ui 1.1.0.
Can this be closed?

**Comment by gaktive** [comment]
@kravciak if that's the case, then go ahead and close this.
