### ISSUE TITLE
Re-enable and fix e2e tests that take user away from dashboard

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9417]
- cypress/e2e/tests/pages/home.spec.ts `Can click on support links`
  - ranchermanager.docs.rancher.com
  - slack.rancher.io
- tests disabled as part of bump to cypress 10.11.0 and pending release
  - as part of that i've fixed the cy.origin for them both
  - however now it throws context based error (see below)

```
  1) Home Page
       "before each" hook for "Can click on support links":
     CypressError: `cy.scrollIntoView()` failed because it requires a DOM element.
The subject received was:
  > `undefined`
The previous command that ran was:
  > `cy.get()`
Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Home Page`
      at ensureElement (https://127.0.0.1/__cypress/runner/cypress_runner.js:147634:76)
      at validateType (https://127.0.0.1/__cypress/runner/cypress_runner.js:147457:16)
      at $Cy.ensureSubjectByType (https://127.0.0.1/__cypress/runner/cypress_runner.js:147493:9)
      at $Cy.pushSubject (https://127.0.0.1/__cypress/runner/cypress_runner.js:158018:12)
      at wrapped (https://127.0.0.1/__cypress/runner/cypress_runner.js:157507:19)
  From Your Spec Code:
      at HomeClusterListPo.checkVisible (webpack:///./cypress/e2e/po/components/component.po.ts:39:23)
      at HomePagePo.goToAndWaitForGet (webpack:///./cypress/e2e/po/pages/home.po.ts:26:20)
      at Context.eval (webpack:///./cypress/e2e/tests/pages/home.spec.ts:14:15)
```

**Comment by yonasberhe23** [comment]
fixed in https://github.com/rancher/dashboard/pull/9421
